"""empty message

Revision ID: 64217caf9455
Revises: 65d35ed1a23a
Create Date: 2024-01-10 13:30:10.851686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64217caf9455'
down_revision = '65d35ed1a23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
