"""empty message

Revision ID: 65d35ed1a23a
Revises: 6d19f36b0f9c
Create Date: 2024-01-05 15:37:41.750075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d35ed1a23a'
down_revision = '6d19f36b0f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poast_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('children', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poast_table', schema=None) as batch_op:
        batch_op.drop_column('children')

    # ### end Alembic commands ###
