"""empty message

Revision ID: 6d19f36b0f9c
Revises: d96db9ab40fd
Create Date: 2024-01-04 15:37:48.837137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d19f36b0f9c'
down_revision = 'd96db9ab40fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poast_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_poast_table_ancestor_id_poast_table', type_='foreignkey')
        batch_op.drop_column('ancestor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poast_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ancestor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_poast_table_ancestor_id_poast_table', 'poast_table', ['ancestor_id'], ['id'])

    # ### end Alembic commands ###
