"""empty message

Revision ID: 83f2d6959712
Revises: bff5dd35c0e4
Create Date: 2024-01-04 13:43:39.164542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f2d6959712'
down_revision = 'bff5dd35c0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['user_table.id'], name=op.f('fk_reader_table_reader_id_user_table')),
    sa.ForeignKeyConstraint(['writer_id'], ['writer_table.id'], name=op.f('fk_reader_table_writer_id_writer_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writer_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True, back_populates='writes_as'),
    sa.ForeignKeyConstraint(['reader_id'], ['reader_table.id'], name=op.f('fk_writer_table_reader_id_reader_table')),
    sa.ForeignKeyConstraint(['writer_id'], ['user_table.id'], name=op.f('fk_writer_table_writer_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follow_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.Column('followed_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_table.id'], name='fk_follow_table_followed_id_user_table'),
    sa.ForeignKeyConstraint(['follower_id'], ['user_table.id'], name='fk_follow_table_follower_id_user_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('writer_table')
    op.drop_table('reader_table')
    # ### end Alembic commands ###
