"""empty message

Revision ID: a829476278e8
Revises: 83f2d6959712
Create Date: 2024-01-04 14:41:52.172428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a829476278e8'
down_revision = '83f2d6959712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['user_table.id'], name=op.f('fk_follow_table_reader_id_user_table')),
    sa.ForeignKeyConstraint(['writer_id'], ['user_table.id'], name=op.f('fk_follow_table_writer_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('writer_table')
    op.drop_table('reader_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reader_id', sa.INTEGER(), nullable=True),
    sa.Column('writer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['user_table.id'], name='fk_reader_table_reader_id_user_table'),
    sa.ForeignKeyConstraint(['writer_id'], ['writer_table.id'], name='fk_reader_table_writer_id_writer_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writer_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reader_id', sa.INTEGER(), nullable=True),
    sa.Column('writer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['reader_table.id'], name='fk_writer_table_reader_id_reader_table'),
    sa.ForeignKeyConstraint(['writer_id'], ['user_table.id'], name='fk_writer_table_writer_id_user_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follow_table')
    # ### end Alembic commands ###
