"""empty message

Revision ID: bff5dd35c0e4
Revises: 
Create Date: 2024-01-04 12:49:17.069617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff5dd35c0e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('follow_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_table.id'], name=op.f('fk_follow_table_followed_id_user_table')),
    sa.ForeignKeyConstraint(['follower_id'], ['user_table.id'], name=op.f('fk_follow_table_follower_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('notetext', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['user_table.id'], name=op.f('fk_notification_table_target_user_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poast_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ancestor_id', sa.Integer(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ancestor_id'], ['poast_table.id'], name=op.f('fk_poast_table_ancestor_id_poast_table')),
    sa.ForeignKeyConstraint(['parent_id'], ['poast_table.id'], name=op.f('fk_poast_table_parent_id_poast_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_poast_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentioned_id', sa.Integer(), nullable=True),
    sa.Column('mentioner_id', sa.Integer(), nullable=True),
    sa.Column('poast_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_id'], ['user_table.id'], name=op.f('fk_mention_table_mentioned_id_user_table')),
    sa.ForeignKeyConstraint(['mentioner_id'], ['user_table.id'], name=op.f('fk_mention_table_mentioner_id_user_table')),
    sa.ForeignKeyConstraint(['poast_id'], ['poast_table.id'], name=op.f('fk_mention_table_poast_id_poast_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thumbs_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poast_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poast_id'], ['user_table.id'], name=op.f('fk_thumbs_up_poast_id_user_table')),
    sa.ForeignKeyConstraint(['user_id'], ['poast_table.id'], name=op.f('fk_thumbs_up_user_id_poast_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbs_up')
    op.drop_table('mention_table')
    op.drop_table('poast_table')
    op.drop_table('notification_table')
    op.drop_table('follow_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
